### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by catpreneur** [james4k/rcon#3]
Hi,

I'm using your library in my pull request for Telegraf https://github.com/influxdata/telegraf/pull/8525

Unfortunately, since this repo does not have a license, I don't believe we can redistribute it legally, as per Github

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

Thank you

**Comment by james4k** [comment]
Sorry about that, added an MIT license. https://github.com/james4k/rcon/commit/34a67ca2b2d65052cacddc7a1415b568f8b932a1

**Comment by catpreneur** [comment]
thank you so much!
